#ifndef __SCRYPT_INC_TYPES__
#define __SCRYPT_INC_TYPES__

#include <stddef.h>

#if _WIN32
  #ifdef SCRYPT_EXPORT
    #define SCRYPT_API __declspec(dllexport)
  #else
    #define SCRYPT_API __declspec(dllimport)
  #endif
#else
  #define SCRYPT_API
#endif

typedef unsigned char byte;
typedef unsigned int word32;

typedef struct SCryptCipherCtx SCryptCipherCtx;
typedef struct SCryptDigestCtx SCryptDigestCtx;
typedef struct SCryptHmacCtx SCryptHmacCtx;

typedef struct SCryptMlKemKey SCryptMlKemKey;
typedef struct SCryptMlDsaKey SCryptMlDsaKey;

enum {
    SCRYPT_DECRYPTION = 0,
    SCRYPT_ENCRYPTION = 1,
};

enum {
    SCRYPT_CIPHER_ALG_NODE = 0x00,
    SCRYPT_CIPHER_ALG_AES  = 0x01
};

enum {
    SCRYPT_CIPHER_BLKSIZE_64  = (0x01 << 8),
    SCRYPT_CIPHER_BLKSIZE_128 = (0x02 << 8),
    SCRYPT_CIPHER_BLKSIZE_256 = (0x03 << 8),
    SCRYPT_CIPHER_BLKSIZE_512 = (0x04 << 8),
};

enum {
    SCRYPT_CIPHER_KEYSIZE_64  = (0x01 << 12),
    SCRYPT_CIPHER_KEYSIZE_128 = (0x02 << 12),
    SCRYPT_CIPHER_KEYSIZE_192 = (0x03 << 12),
    SCRYPT_CIPHER_KEYSIZE_256 = (0x04 << 12),
};

enum {
    SCRYPT_CIPHER_MODE_CBC = (0x02 << 16),
    SCRYPT_CIPHER_MODE_GCM = (0x04 << 16),
    SCRYPT_CIPHER_MODE_XTS = (0x09 << 16),
};

enum {
    SCRYPT_CIPHER_MASK_ALG     = 0x000000FF,
    SCRYPT_CIPHER_MASK_BLKSIZE = 0x00000F00,
    SCRYPT_CIPHER_MASK_KEYSIZE = 0x0000F000,
    SCRYPT_CIPHER_MASK_MODE    = 0x000F0000,
};

typedef enum {
    CIPHER_TYPE_NONE = 0x00,

    CIPHER_TYPE_AES_256_CBC = (SCRYPT_CIPHER_ALG_AES | SCRYPT_CIPHER_BLKSIZE_128 | SCRYPT_CIPHER_KEYSIZE_256 | SCRYPT_CIPHER_MODE_CBC),
    CIPHER_TYPE_AES_256_XTS = (SCRYPT_CIPHER_ALG_AES | SCRYPT_CIPHER_BLKSIZE_128 | SCRYPT_CIPHER_KEYSIZE_256 | SCRYPT_CIPHER_MODE_XTS),
    CIPHER_TYPE_AES_256_GCM = (SCRYPT_CIPHER_ALG_AES | SCRYPT_CIPHER_BLKSIZE_128 | SCRYPT_CIPHER_KEYSIZE_256 | SCRYPT_CIPHER_MODE_GCM),
} SCryptCipherType;

enum {
    SCRYPT_DIGEST_ALG_NONE = 0x00,
    SCRYPT_DIGEST_ALG_SHA2 = 0x02,
    SCRYPT_DIGEST_ALG_SHA3 = 0x03
};

enum {
    SCRYPT_DIGEST_BLKSIZE_16  = (0x01 << 8),
    SCRYPT_DIGEST_BLKSIZE_64  = (0x02 << 8),
    SCRYPT_DIGEST_BLKSIZE_72  = (0x03 << 8),
    SCRYPT_DIGEST_BLKSIZE_104 = (0x04 << 8),
    SCRYPT_DIGEST_BLKSIZE_128 = (0x05 << 8),
    SCRYPT_DIGEST_BLKSIZE_136 = (0x06 << 8),
    SCRYPT_DIGEST_BLKSIZE_144 = (0x07 << 8),
};

enum {
    SCRYPT_DIGEST_SIZE_16   = (0x01 << 16),
    SCRYPT_DIGEST_SIZE_20   = (0x02 << 16),
    SCRYPT_DIGEST_SIZE_28   = (0x03 << 16),
    SCRYPT_DIGEST_SIZE_32   = (0x04 << 16),
    SCRYPT_DIGEST_SIZE_48   = (0x05 << 16),
    SCRYPT_DIGEST_SIZE_64   = (0x06 << 16),
    SCRYPT_DIGEST_SIZE_1_32 = (0x07 << 16),
    SCRYPT_DIGEST_SIZE_1_64 = (0x08 << 16),
};

typedef enum {
    DIGEST_TYPE_NONE         = 0x00,
    
    DIGEST_TYPE_SHA256       = (SCRYPT_DIGEST_ALG_SHA2 | SCRYPT_DIGEST_BLKSIZE_64  | SCRYPT_DIGEST_SIZE_32),
    DIGEST_TYPE_SHA384       = (SCRYPT_DIGEST_ALG_SHA2 | SCRYPT_DIGEST_BLKSIZE_128 | SCRYPT_DIGEST_SIZE_48),
    DIGEST_TYPE_SHA512       = (SCRYPT_DIGEST_ALG_SHA2 | SCRYPT_DIGEST_BLKSIZE_128 | SCRYPT_DIGEST_SIZE_64),

    DIGEST_TYPE_SHA3_256     = (SCRYPT_DIGEST_ALG_SHA3 | SCRYPT_DIGEST_BLKSIZE_136 | SCRYPT_DIGEST_SIZE_32),
    DIGEST_TYPE_SHA3_384     = (SCRYPT_DIGEST_ALG_SHA3 | SCRYPT_DIGEST_BLKSIZE_104 | SCRYPT_DIGEST_SIZE_48),
    DIGEST_TYPE_SHA3_512     = (SCRYPT_DIGEST_ALG_SHA3 | SCRYPT_DIGEST_BLKSIZE_72  | SCRYPT_DIGEST_SIZE_64),
} SCryptDigestType;

enum {
    SCRYPT_DIGEST_MASK_ALG     = 0x000000FF,
    SCRYPT_DIGEST_MASK_BLKSIZE = 0x0000FF00,
    SCRYPT_DIGEST_MASK_SIZE    = 0x00FF0000,
};

typedef enum {
    SCRYPT_KEY_TYPE_NONE = 0x00,
    SCRYPT_KEY_TYPE_PRIVATE,
    SCRYPT_KEY_TYPE_PUBLIC,
} SCryptAsymKeyType;

typedef enum {
    MLKEM_LEVEL_3,
    MLKEM_LEVEL_5,
} SCryptMlKemLevel;

typedef enum {
    MLDSA_LEVEL_3,
    MLDSA_LEVEL_5,
} SCryptMlDsaLevel;

#endif
